sudo: required

language: php
php:
  - '7.0'

stages:
  - analyse
  - test

jobs:
  include:

    - stage: analyse
      env:
        - TEST=phplint
      before_script:
        - composer install
      script:
        - composer analyse:phplint

    - stage: analyse
      env:
        - TEST=phpcs
      before_script:
        - composer install
      script:
        - composer analyse:phpcs

    - stage: test
      env:
        - TEST=phpunit
      before_script:
        - composer install
      script:
        - composer test:phpunit
      after_success:
        - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    - https://h2a-hubot.herokuapp.com/webhooks/travis
